[package]
name = "contranomy-loaded-program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv-rt = "0.8.0"
contranomy-debug = { path = "../contranomy-rs-crates/contranomy-debug" }
